SELECT DISTINCT
    REPLACE(SPLETIVO.CODPERLET,'/','-') AS CATPERIODO,
    SPLETIVO.IDPERLET AS IDPERLET,
    GCOLIGADA.CODCOLIGADA AS CODCOLIGADA,
    GCOLIGADA.NOMEFANTASIA AS COLIGADA,
    STIPOCURSO.NOME AS CATMODALIDADE,
    UPPER(SDISCIPLINA.NOME) AS FULLNAME,
    REPLACE(SPLETIVO.CODPERLET,'/','-') AS PERIODO,
    UPPER(SCURSO.NOME) AS CURSO,
	SCURSO.CODCURSO,
	STURMADISC.IDTURMADISC,
    STURMADISC.CODTURMA,
    STURMADISC.CODTIPOCURSO AS FILIAL,
	SHABILITACAOFILIAL.IDHABILITACAOFILIAL,
    CONCAT(GCOLIGADA.CODCOLIGADA,'-',STURMADISC.IDTURMADISC) AS SHORTNAME,
    CONCAT(GCOLIGADA.CODCOLIGADA,'-',STURMADISC.IDTURMADISC) AS IDNUMBER
FROM STURMADISC WITH (NOLOCK)
INNER JOIN SPLETIVO WITH (NOLOCK)
    ON SPLETIVO.IDPERLET = STURMADISC.IDPERLET
   AND SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
INNER JOIN GCOLIGADA WITH (NOLOCK)
    ON GCOLIGADA.CODCOLIGADA = SPLETIVO.CODCOLIGADA
INNER JOIN SHABILITACAOFILIAL WITH (NOLOCK)
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
   AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
   AND SHABILITACAOFILIAL.CODFILIAL = STURMADISC.CODFILIAL
INNER JOIN STIPOCURSO WITH (NOLOCK)
    ON STIPOCURSO.CODTIPOCURSO = STURMADISC.CODTIPOCURSO
   AND STIPOCURSO.CODCOLIGADA = STURMADISC.CODCOLIGADA
INNER JOIN SCURSO WITH (NOLOCK)
    ON SCURSO.CODCOLIGADA = STURMADISC.CODCOLIGADA
   AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
   AND SCURSO.CODTIPOCURSO = STURMADISC.CODTIPOCURSO
INNER JOIN SDISCIPLINA WITH (NOLOCK)
    ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
   AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
WHERE
    STURMADISC.DISPONIVELMATRICULA = 'S'
    AND STURMADISC.ATIVA = 'S'
	AND REPLACE(SPLETIVO.CODPERLET,'/','-') NOT IN ('UNICO','único','ÚNICO','Pós','MI','MII','MIII','MIV','MV','1')
	AND GCOLIGADA.CODCOLIGADA NOT IN ('6','2','4')
	AND LEFT(SPLETIVO.CODPERLET, 4) > '2025'