SELECT 
    GCOLIGADA.CODCOLIGADA AS CODCOLIGADA,
    GCOLIGADA.NOMEFANTASIA AS COLIGADA
FROM GCOLIGADA WITH (NOLOCK)
WHERE GCOLIGADA.NOMEFANTASIA NOT IN (
    'ALBUQUERQUE COMERCIO DE VESTUARIOS E SERVICOS ADMINISTRATIVOS LTDA',
    'REDE RIOS DE COMUNICACAO LTDA',
    'RADIO BARE LTDA',
    'KLG ASSESSORIA EMPRESARIAL',
    'GB LIRA',
    'ALENCAR ASSESSORIA EMPRESARIAL',
    'JB LIRA',
    'LC ASSESSORIA EMPRESARIAL',
    'F A FIDELIS ASSESSORIA EMPRESARIAL',
    'LEAL',
    'CCBRAGA',
    'CBLIRA',
    'IMEEX'
)
ORDER BY GCOLIGADA.CODCOLIGADA;