SELECT  /*top 5*/
			STURMADISC.CODCOLIGADA
			,SPLETIVO.IDPERLET
			, STURMADISC.CODFILIAL
			, STURMADISC.CODTIPOCURSO
			, SCURSO.CODCURSO
			, UPPER(SCURSO.NOME) CURSO
            ,STIPOCURSO.NOME as NE
            ,GFILIAL.NOME as FL
			, CASE
				WHEN TURMAGERENCIAL.CODTURMA IS NULL THEN STURMADISC.CODTURMA
				ELSE TURMAGERENCIAL.CODTURMA
			  END CODTURMA
			, SMATRICPL.RA AS userid
			, '0' AS suspend
			, STURMADISC.CODDISC
			, CONCAT(STURMADISC.CODCOLIGADA,'-',CASE
													WHEN TURMAGERENCIAL.IDTURMADISC IS NULL THEN STURMADISC.IDTURMADISC
													ELSE TURMAGERENCIAL.IDTURMADISC END) courseid
			, '5' AS roleid /*ID do role retirado do Moodle*/
			, SSTATUS.DESCRICAO STATUS_DISC
			, SS.DESCRICAO STATUS_PERIODO
			/*cohort*/
			, UPPER(SCURSO.NOME) AS cohort1
			, UPPER(STIPOCURSO.NOME) AS cohort2
			, STURMADISC.CODTURMA AS cohort3


		FROM STURMADISC (NOLOCK)
			LEFT JOIN STURMADISCCOMPL			(NOLOCK) ON STURMADISC.CODCOLIGADA = STURMADISCCOMPL.CODCOLIGADA AND STURMADISC.IDTURMADISC = STURMADISCCOMPL.IDTURMADISC
			INNER JOIN SPLETIVO					(NOLOCK) ON STURMADISC.CODCOLIGADA = SPLETIVO.CODCOLIGADA AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET
			INNER JOIN SMATRICULA				(NOLOCK) ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
			INNER JOIN SSTATUS					(NOLOCK) ON SMATRICULA.CODCOLIGADA = SSTATUS.CODCOLIGADA AND SMATRICULA.CODSTATUS = SSTATUS.CODSTATUS
			INNER JOIN ZMDSSTATUSSTATUSGLOBAL	(NOLOCK) ON SSTATUS.CODCOLIGADA = ZMDSSTATUSSTATUSGLOBAL.CODCOLIGADA AND SSTATUS.CODSTATUS = ZMDSSTATUSSTATUSGLOBAL.CODSTATUS
			INNER JOIN SMATRICPL				(NOLOCK) ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET AND SMATRICULA.RA = SMATRICPL.RA
														AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
			INNER JOIN SSTATUS SS				(NOLOCK) ON SMATRICPL.CODCOLIGADA = SS.CODCOLIGADA AND SMATRICPL.CODSTATUS = SS.CODSTATUS
			INNER JOIN ZMDSSTATUSSTATUSGLOBAL Z (NOLOCK) ON SS.CODCOLIGADA = Z.CODCOLIGADA AND SS.CODSTATUS = Z.CODSTATUS
			INNER JOIN SHABILITACAOFILIAL		(NOLOCK) ON SMATRICPL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
			INNER JOIN SCURSO					(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
			LEFT JOIN STURMADISCGERENCIADA		(NOLOCK) ON STURMADISCGERENCIADA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND STURMADISCGERENCIADA.IDTURMADISCGERENCIADA = STURMADISC.IDTURMADISC
			LEFT JOIN STURMADISC TURMAGERENCIAL (NOLOCK) ON TURMAGERENCIAL.CODCOLIGADA = STURMADISCGERENCIADA.CODCOLIGADA AND TURMAGERENCIAL.IDTURMADISC = STURMADISCGERENCIADA.IDTURMADISC
		    INNER JOIN STIPOCURSO				(NOLOCK) ON STURMADISC.CODCOLIGADA = STIPOCURSO.CODCOLIGADA AND STURMADISC.CODTIPOCURSO = STIPOCURSO.CODTIPOCURSO
			INNER JOIN GCOLIGADA (NOLOCK) ON GCOLIGADA.CODCOLIGADA = STURMADISC.CODCOLIGADA
	        INNER JOIN GFILIAL (NOLOCK) ON GFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA AND GFILIAL.CODFILIAL = STURMADISC.CODFILIAL


		WHERE   STURMADISC.TIPO = 'P' /*TRAZER OS ALUNOS PRESENCIAIS PARA INCLUSÃO NO DIGITAL FAMETRO*/
		AND LEFT(SPLETIVO.CODPERLET, 4) > '2025'
		AND NOT(SMATRICULA.CODCOLIGADA = 1 AND SHABILITACAOFILIAL.CODTIPOCURSO in (85))
		--  AND STURMADISC.CODTURMA  = 'ADM232N01-SED'
		AND ZMDSSTATUSSTATUSGLOBAL.IDSTATUSGLOBAL IN (28,1) /*MATRICULADO*/ /*DISCIPLINA*/
		/*AND SMATRICULA.CODCOLIGADA = 3*/