SELECT DISTINCT
    REPLACE(SPLETIVO.CODPERLET,'/','-') AS CATPERIODO,
    SPLETIVO.IDPERLET AS IDPERLET,
    GCOLIGADA.CODCOLIGADA AS CODCOLIGADA,
    CONCAT(REPLACE(SPLETIVO.CODPERLET,'/','-'),' | ',STIPOCURSO.NOME) AS LABELPERIODO
FROM STURMADISC WITH (NOLOCK)
INNER JOIN SPLETIVO WITH (NOLOCK)
    ON SPLETIVO.IDPERLET = STURMADISC.IDPERLET
   AND SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
INNER JOIN GCOLIGADA WITH (NOLOCK)
    ON GCOLIGADA.CODCOLIGADA = SPLETIVO.CODCOLIGADA
INNER JOIN SHABILITACAOFILIAL WITH (NOLOCK)
    ON SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
   AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
   AND SHABILITACAOFILIAL.CODFILIAL = STURMADISC.CODFILIAL
INNER JOIN STIPOCURSO WITH (NOLOCK)
    ON STIPOCURSO.CODTIPOCURSO = STURMADISC.CODTIPOCURSO
   AND STIPOCURSO.CODCOLIGADA = STURMADISC.CODCOLIGADA
WHERE
    STURMADISC.DISPONIVELMATRICULA = 'S'
    AND STURMADISC.ATIVA = 'S'
    AND REPLACE(SPLETIVO.CODPERLET,'/','-') NOT IN ('UNICO','único','ÚNICO','Pós','MI','MII','MIII','MIV','MV','1')
    AND SPLETIVO.CODPERLET LIKE '[0-9][0-9][0-9][0-9]%'
    AND LEFT(SPLETIVO.CODPERLET, 4) > '2025'