               SELECT   DISTINCT
                   lower(CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN PPESSOA_PROF_GERENCIAL.CODUSUARIO ELSE PPESSOA_PROF.CODUSUARIO END) AS USERNAME
                   ,'rm'                                auth
               
                   ,CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN PPESSOA_PROF_GERENCIAL.CPF ELSE PPESSOA_PROF.CPF END AS 'PASSWORD',
                   CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN
                       UPPER(CASE WHEN CHARINDEX(' ', LTRIM(RTRIM(PPESSOA_PROF_GERENCIAL.NOME))) > 0 THEN LEFT(PPESSOA_PROF_GERENCIAL.NOME,
                       CHARINDEX(' ', LTRIM(RTRIM(PPESSOA_PROF_GERENCIAL.NOME))) - 1) ELSE PPESSOA_PROF_GERENCIAL.NOME END)  ELSE
               
                       UPPER(CASE WHEN CHARINDEX(' ', LTRIM(RTRIM(PPESSOA_PROF.NOME))) > 0 THEN LEFT(PPESSOA_PROF.NOME,
                       CHARINDEX(' ', LTRIM(RTRIM(PPESSOA_PROF.NOME))) - 1) ELSE PPESSOA_PROF.NOME END) END AS FIRSTNAME,
               
               /*	CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN
                       PPESSOA_PROF_GERENCIAL.NOME ELSE PPESSOA_PROF.NOME END AS PROFESSORNOME,
                       SPROFESSOR.CODPROF,*/
               
                    CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN
                       SUBSTRING(LTRIM(RTRIM(PPESSOA_PROF_GERENCIAL.NOME)), CHARINDEX(' ', LTRIM(RTRIM(PPESSOA_PROF_GERENCIAL.NOME))) + 1, 50)
                       ELSE
                       SUBSTRING(LTRIM(RTRIM(PPESSOA_PROF.NOME)), CHARINDEX(' ', LTRIM(RTRIM(PPESSOA_PROF.NOME))) + 1, 50) END  AS LASTNAME,
               
                   CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN
                       LOWER(CASE WHEN PPESSOA_PROF_GERENCIAL.EMAIL IS NULL THEN CONCAT(PROFESSOR_GERENCIAL.CODPROF, '@default.com.br') WHEN PPESSOA_PROF_GERENCIAL.EMAIL = '' THEN CONCAT(PROFESSOR_GERENCIAL.CODPROF, '@default.com.br') WHEN PPESSOA_PROF_GERENCIAL.EMAIL = '-' THEN CONCAT(PROFESSOR_GERENCIAL.CODPROF,
                                         '@default.com.br') WHEN PPESSOA_PROF_GERENCIAL.EMAIL = '---' THEN CONCAT(PROFESSOR_GERENCIAL.CODPROF, '@default.com.br') ELSE PPESSOA_PROF_GERENCIAL.EMAIL END)
                                   ELSE
                       LOWER(CASE WHEN PPESSOA_PROF.EMAIL IS NULL THEN CONCAT(SPROFESSOR.CODPROF, '@default.com.br') WHEN PPESSOA_PROF.EMAIL = '' THEN CONCAT(SALUNO.RA, '@default.com.br') WHEN PPESSOA_PROF.EMAIL = '-' THEN CONCAT(SPROFESSOR.CODPROF,
                                         '@default.com.br') WHEN PPESSOA_PROF.EMAIL = '---' THEN CONCAT(SPROFESSOR.CODPROF, '@default.com.br') ELSE PPESSOA_PROF.EMAIL END) END AS EMAIL,
                   (CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN PPESSOA_PROF_GERENCIAL.CPF ELSE PPESSOA_PROF.CPF END)   profile_field_CPF
               /*
                    CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN
                       CONVERT(VARCHAR, TURMAGERENCIAL.CODCOLIGADA)+ '-'+ CONVERT(VARCHAR(200), TURMAGERENCIAL.IDTURMADISC)
                       ELSE
                       CONVERT(VARCHAR, STURMADISC.CODCOLIGADA)+ '-'+ CONVERT(VARCHAR(200), STURMADISC.IDTURMADISC) END AS CODDISC_MOODLE,
                       SCURSOTURMA.NOME AS CURSOTURMA,
               CASE WHEN STURMADISCGERENCIADA.IDTURMADISCGERENCIADA IS NOT NULL THEN PPESSOA_PROF_GERENCIAL.CODUSUARIO ELSE PPESSOA_PROF.CODUSUARIO END AS USUARIO,
               'PROFESSOR' AS PAPEL, SDISCIPLINA.NOME AS DISCIPLINA*/
               ,SMATRICPL.CODCOLIGADA
               FROM STURMADISC (NOLOCK)
                   LEFT JOIN STURMADISCCOMPL (NOLOCK) ON STURMADISCCOMPL.CODCOLIGADA = STURMADISC.CODCOLIGADA AND STURMADISCCOMPL.IDTURMADISC = STURMADISC.IDTURMADISC
                   INNER JOIN SPLETIVO (NOLOCK) ON STURMADISC.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET
                   INNER JOIN SDISCIPLINA (NOLOCK) ON STURMADISC.CODCOLIGADA=SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC=SDISCIPLINA.CODDISC
                   INNER JOIN SMATRICULA (NOLOCK) ON STURMADISC.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SMATRICULA.IDTURMADISC
                   INNER JOIN SSTATUS (NOLOCK) ON SSTATUS.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SSTATUS.CODSTATUS=SMATRICULA.CODSTATUS
                   INNER JOIN SMATRICPL (NOLOCK) ON SMATRICPL.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SMATRICPL.RA=SMATRICULA.RA AND SMATRICPL.IDPERLET=SMATRICULA.IDPERLET
                               AND SMATRICPL.IDHABILITACAOFILIAL=SMATRICULA.IDHABILITACAOFILIAL
                   INNER JOIN SALUNO (NOLOCK) ON SALUNO.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SALUNO.RA=SMATRICPL.RA
                   INNER JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO=SALUNO.CODPESSOA
                   INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL=STURMADISC.IDHABILITACAOFILIAL
                   LEFT OUTER JOIN SHABILITACAO (NOLOCK)  ON SHABILITACAO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SHABILITACAO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
                       AND SHABILITACAO.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
                   INNER JOIN SCURSO (NOLOCK) ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
                   INNER JOIN STIPOCURSO (NOLOCK) ON STIPOCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND STIPOCURSO.CODTIPOCURSO=SHABILITACAOFILIAL.CODTIPOCURSO
                   LEFT JOIN STURMADISCGERENCIADA (NOLOCK) ON STURMADISCGERENCIADA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND STURMADISCGERENCIADA.IDTURMADISCGERENCIADA = STURMADISC.IDTURMADISC
               
                   LEFT JOIN SPROFESSORTURMA  (NOLOCK)  ON SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
                                                   AND STURMADISC.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
               
                   LEFT JOIN SPROFESSOR  (NOLOCK)   ON STURMADISC.CODCOLIGADA = SPROFESSOR.CODCOLIGADA AND SPROFESSORTURMA.CODPROF = SPROFESSOR.CODPROF
                   LEFT JOIN PPESSOA     PPESSOA_PROF (NOLOCK)   ON SPROFESSOR.CODPESSOA = PPESSOA_PROF.CODIGO
               
                   LEFT JOIN STURMADISC TURMAGERENCIAL (NOLOCK) ON TURMAGERENCIAL.CODCOLIGADA = STURMADISCGERENCIADA.CODCOLIGADA AND TURMAGERENCIAL.IDTURMADISC = STURMADISCGERENCIADA.IDTURMADISC
                   LEFT JOIN SPROFESSORTURMA  PROFESSORTURMA_GERENCIAL (NOLOCK)  ON PROFESSORTURMA_GERENCIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA AND PROFESSORTURMA_GERENCIAL.IDTURMADISC = TURMAGERENCIAL.IDTURMADISC
                   LEFT JOIN SPROFESSOR  PROFESSOR_GERENCIAL (NOLOCK)   ON STURMADISC.CODCOLIGADA = PROFESSOR_GERENCIAL.CODCOLIGADA AND PROFESSORTURMA_GERENCIAL.CODPROF = PROFESSOR_GERENCIAL.CODPROF
                   LEFT JOIN PPESSOA     PPESSOA_PROF_GERENCIAL (NOLOCK)   ON PROFESSOR_GERENCIAL.CODPESSOA = PPESSOA_PROF_GERENCIAL.CODIGO
                   INNER JOIN SHABILITACAOFILIAL SHABCURSO (NOLOCK) ON SHABCURSO.CODCOLIGADA=STURMADISC.CODCOLIGADA AND SHABCURSO.IDHABILITACAOFILIAL=STURMADISC.IDHABILITACAOFILIAL
                   INNER JOIN SCURSO SCURSOTURMA (NOLOCK) ON SCURSOTURMA.CODCOLIGADA=SHABCURSO.CODCOLIGADA AND SCURSOTURMA.CODCURSO=SHABCURSO.CODCURSO
                   INNER JOIN GCOLIGADA (NOLOCK) ON GCOLIGADA.CODCOLIGADA = STURMADISC.CODCOLIGADA
                   INNER JOIN GFILIAL (NOLOCK) ON GFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA AND GFILIAL.CODFILIAL = STURMADISC.CODFILIAL
               
               WHERE ((SCURSO.CURPRESDIST = 'p' AND STURMADISC.TIPO = 'P') or (SCURSO.CURPRESDIST = 'd'AND STURMADISC.TIPO = 'P' ))
               AND SPLETIVO.CODPERLET IN ('2026/1')
               AND SPROFESSORTURMA.TIPOPROF = 'T'
               AND ISNUMERIC(PPESSOA_PROF.CODUSUARIO) = 0
               AND (UPPER(SSTATUS.DESCRICAO) LIKE 'MATRIC%')
               AND PPESSOA_PROF.CPF is not null
               AND PPESSOA_PROF.CODUSUARIO is not null